aduseradmin/urls.py
from django.urls import path
from .  import  views

app_name = "aduseradmin"
urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('register/', views.registerPage, name='register'),
   
    # universal views for logged in users
    path('logout/', views.logoutPage, name='logout'),
    path('account/', views.accountPage, name='account'),

    # Administration of Accounts (Staff_only)
    # path('admin/', views.adminPage, name='admin'),
    
    # groups
    path('groups/create', views.createGroup, name='group_create'),
    path('groups/<int:pk>/delete', views.deleteGroup, name='group_delete'),
    path('groups/<int:pk>/update', views.updateGroup, name='group_upate'),

    # users
    path('user/<int:pk>/view', views.viewUser, name='user_view'),
    path('user/<int:pk>/delete', views.deleteUser, name='user_delete'),
    path('user/<int:pk>/update', views.updateUser, name='user_update'),
    path('createuser/', views.createUser, name='user_create'),
]

bbwdesk/urls.py
from django.urls import path

from . import views
from . import restViews

app_name = 'bbwdesk'
urlpatterns = [
     # index
     path('', views.index, name='index'), #user dashboard
     path('adminboard/', views.adminPage, name='admin'),
     # task 
     path('taskcreate/', views.task_create, name='task_create'),
     path('<int:pk>/edit/', views.task_edit, name='task_edit'),
     path('<int:pk>/delete/', views.task_delete, name='task_delete'),
     path('<int:pk>/view/', views.TaskDetail.as_view(), 
          {'task_list.html':'bbwdesk/task_view_content.html'}, name='task_view'),
     path('<int:pk>/submit/', views.taskSubmitPage, name='task_submit'),
     # assignment Urls
     path('assignment/<int:pk>/', views.assignmentPage, name='assginment_view'),

     # API
     path('getGroupList/', views.getGroupList, name='ajax_grouplist'),
     path('objByAssignId/', views.getObjectsbyAssignment),
     path('assign/', restViews.AssignmentSet.as_view(), name='AssignmentSet'),
     path('assign/<int:pk>', restViews.AssignmentDetail.as_view(), name='AssignmentDetail'),
     path('assignNested/', restViews.AssignmentNestedSet.as_view(), name='NestedAssignmentSet'),
     path('userSet/', restViews.ExtendedUserSet.as_view(), name='UserSet'),
     path('assignObjSet/', restViews.AssignmentObjectSet.as_view(), name='AssignObjSet'),
]

fiaehome/urls.py
from django.contrib import admin
from django.urls import path, include 

app_name='fiaehome'
urlpatterns = [
    path('', include('bbwdesk.urls')),
    path('admin/', admin.site.urls),
    path('', include('aduseradmin.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

bbwdesk/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class UserDetail(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE, related_name='detail')
    initals = models.CharField(max_length=4)

    def __str__(self):
        return self.initals


# All Assignment related models

class Assignment(models.Model):
    name = models.CharField(max_length=40, default="Assignment")
    editor = models.ForeignKey(User, on_delete=models.CASCADE, related_name="assign_editor")
    creation_date = models.DateField(default=timezone.now)
    actors = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return self.name


# TODO: Needs more generic expression for searching a foreign key relation
class AssignmentObject(models.Model):
    assignment_id = models.ForeignKey(Assignment, on_delete=models.CASCADE, related_name="assignObjects")

    def __str__(self):
        try:
            task = Task.objects.get(object_id=self.id)
        except Task.DoesNotExist:
            return "Unassigned"

        return "Assignment-Object: " + task.title


# AssingmentObjects Subcategory Models

class Task(models.Model):
    object_id = models.OneToOneField(AssignmentObject, null=True,on_delete=models.CASCADE,related_name="taskObject")
    title = models.CharField(max_length=20)
    description = models.TextField(blank=True)
    users = models.ManyToManyField(UserDetail, blank=True)
    priority = models.IntegerField(default=0, 
                                validators=[
                                    MaxValueValidator(5),
                                    MinValueValidator(0),
                                ]
    )
    status = models.IntegerField(default=0, 
                                validators=[
                                    MaxValueValidator(3),
                                    MinValueValidator(0),
                                ]
    )
    progress = models.IntegerField(default=0,
                                    validators=[
                                    MaxValueValidator(10),
                                    MinValueValidator(0),
                                ]
    )
    deadline = models.DateField(default=timezone.now)


    def __str__(self):
        return self.title


# Comment and Submission System

class CommentThread(models.Model):
    id = models.AutoField(primary_key=True)
    object_id = models.OneToOneField(AssignmentObject, null=True,on_delete=models.CASCADE)

class Comment(models.Model):
    user_id = models.ForeignKey(UserDetail, blank=True, null=True, on_delete=models.CASCADE)
    text = models.TextField()
    thread_id = models.ForeignKey(CommentThread, on_delete=models.CASCADE)
    attachement= models.FileField('attachements/', null=True)
    creation_date = models.DateTimeField(default=timezone.now)


class Submission(models.Model):
    thread_id = models.ForeignKey(CommentThread, on_delete=models.CASCADE)
    task_id = models.OneToOneField(Task, on_delete=models.CASCADE)
    user_id = models.ForeignKey(UserDetail, on_delete=models.CASCADE)

bbwdesk/forms.py
from .models import Task
import django.forms as forms

class TaskForm(forms.ModelForm):
    priority = forms.IntegerField(max_value=5, min_value=0)
    status = forms.IntegerField(max_value=3, min_value=0)
    progress = forms.IntegerField(max_value=10,min_value=0)
    deadline = forms.DateField()

    class Meta:
        model = Task
        fields = ('title', 'description', 'users', 'priority', 
                    'status', 'progress', 'deadline')
        widgets = {
            'status': forms.NumberInput(attrs={'value': 0})
        }

bbwdesk/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, JsonResponse
from django.views.generic.edit import DeleteView
from django.views.generic import DetailView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.contrib.auth.models import Group, User


from .models import Task, Assignment, UserDetail, AssignmentObject
from .forms import TaskForm
from .decorators import ajax_required
from .utils import objectToJson

# Create your views here.

@login_required
def index(request):
    assignments = Assignment.objects.filter(actors__in=UserDetail.objects.filter(user=request.user))

    context = {
        'assignments': assignments
    }

    return render(request,'bbwdesk/index_content.html', context)

@login_required
def task_edit(request, pk):     
    if request.method == 'POST':
        try:
            task = Task.objects.get(pk=pk)
            t_form = TaskForm(instance=task, data=request.POST)
        except Task.DoesNotExist:
            raise Http404("Task does not exist")

        if t_form.is_valid():
            u = t_form.save()
            return redirect("bbwdesk:index")
    
    elif request.method == 'GET':
        try:
            task = Task.objects.get(pk=pk)
            t_form = TaskForm(instance=task)
        except Task.DoesNotExist:
            return HttpResponse(status=404)
    
        return render(request, 'bbwdesk/task_edit_content.html', {'form': t_form, 'task': task})

@login_required
def task_delete(request, pk):
    task = get_object_or_404(Task, pk=pk)
    
    if request.method == 'POST': # Confirmed Delete
            task.delete()
            return redirect('bbwdesk:index')
    
    return render(request, 'bbwdesk/task_delete_content.html', {'task' : task })

@login_required
def task_create(request):
    if request.method == "POST":
        t_form = TaskForm(request.POST)

        if t_form.is_valid():
            u = t_form.save()
            return redirect("bbwdesk:index")
    
    else:
        t_form = TaskForm()
        context = {'form': t_form}
        return render(request, 'bbwdesk/task_create_content.html', context)



class TaskDetail(DetailView):
    model = Task


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        instance = super().get_object()

        context['users'] = instance.users.all()

        return context

@login_required
def taskSubmitPage(request, pk):
    return render(request, 'bbwdesk/submission_page_content.html')

@login_required
def assignmentPage(request):
    return HttpResponse("WIP: Assignment View")

"""
    All views for the adminPage
"""

# TODO: Write decorator, that limits access to users with role "Ausbilder"
@login_required
def adminPage(request):
    return render(request, 'bbwdesk/desk_admin_content.html')


# ajax views
@ajax_required
@login_required
def getGroupList(request):
    groups = Group.objects.all()
    json = { "groups" : list() }
    for group in groups:
        group_json = dict()
        group_json['pk'] = group.id
        group_json['name'] = group.name
        
        users = User.objects.filter(groups__id=group.id)
        group_json['users'] = list()
        
        for user in users:
            user_obj = dict()
            user_obj['pk'] = user.id
            user_obj['name'] = user.username
            
            group_json['users'].append(user_obj)

        json["groups"].append(group_json)

    return JsonResponse(json, safe=False)


@ajax_required
@login_required
def getObjectsbyAssignment(request):
    json = {"objects": list()}
    
    if request.method == "GET":
        objects = AssignmentObject.objects.filter(
                                    assignment_id=request.GET["assign_id"])

        for obj in objects:
            obj = Task.objects.get(object_id=obj.id)
            json["objects"].append(objectToJson(obj))

    return JsonResponse(json, safe=False)

bbwdesk/templates/bbwdesk/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        {% load static %}
        <link rel="stylesheet" href="{% static "base/css/bootstrap.min.css" %}">
        <!-- MDB CSS-->
        <link rel="stylesheet" href="{% static "base/css/mdb.min.css" %}">
        <link href="{% static "base/css/addons/datatables.min.css" %}" rel="stylesheet">
        <link href="{% static "base/css/addons/datatables-select2.min.css" %}" rel="stylesheet">

        <!-- Base CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'base/base.css' %}">

        <!-- Site Specifc CSS-->
        {% block css-block %}

        {% endblock%}

        <title>BBWDesk</title>
    </head>

    
    <body>
        <!-- jQuery first, then Popper.js, then Bootstrap JS, then MD Boostrap JS -->
        <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <script type="text/javascript" src="{% static "base/js/mdb.min.js" %}"></script>
        <script type="text/javascript" src="{% static "bbwdesk/js/base.js" %}"></script>
        
         <!--  Cross-Site Navbar-->
        <nav class="navbar navbar-expand-md">
            <a class="navbar-brand" href="{% url "bbwdesk:index" %}">BBWDesk</a>
            <button class="navbar-toggler navbar-dark" type="button" data-toggle="collapse" data-target="#main-navigation">
            <span class="navbar-toggler-icon"></span>
            <span class="hello-msg"></span>
            </button>
            <div class="collapse navbar-collapse" id="main-navigation">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="#">Documentation</a>
                    </li>
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                        <div class="dropdown">
                            <button class="btn-sm btn-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              Hello, {{ request.user }}
                            </button>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
                              <a class="dropdown-item" href="{% url 'bbwdesk:index' %}">Dashboard</a>
                              <a class="dropdown-item" href="{% url 'aduseradmin:account' %}">Accout Management</a>
                              <a class="dropdown-item" href="{% url 'bbwdesk:admin' %}">Admin Page</a>
                              <div class="dropdown-divider"></div>
                              <a class="dropdown-item" href="{% url 'aduseradmin:logout' %}">Logout</a>
                            </div>
                        </div>
                        {% else %}
                        <a class="nav-link" href="{% url 'aduseradmin:login' %}">Login</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </nav>

        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'bbwdesk:index' %}">Home</a></li>
              <li class="breadcrumb-item"><a href="#">Library</a></li>
              <li class="breadcrumb-item active">Data</li>
            </ol>
          </nav>

        {% block content_block %}
        {% endblock %}

        
    </body>
</html>

bbwdesk/templates/bbwdesk/desk_admin_content.html
{% extends 'bbwdesk/base.html' %}
{% load bbwdesk_extras %}
{% load static %}

{% block css-block %}
<link rel="stylesheet" href="{% static "bbwdesk/css/adminPage.css" %}">
{% endblock%}

{% block content_block %}
<!-- DataTables JS -->
<script src="{% static "base/js/addons/datatables2.min.js" %}" type="text/javascript"></script>
<!-- DataTables Select JS -->
<script src="{% static "base/js/addons/datatables-select2.min.js" %}" type="text/javascript"></script>

<script type="text/javascript" src="{% static "bbwdesk/js/modules/DetailView.js" %}"></script>
<script type="text/javascript" src="{% static "bbwdesk/js/adminPage.js" %}"></script>


<div class="container" id="head">
    <h2>Admin-Dashboard</h2>
</div>
<div class="container mt-1 " id="body">
    <div class="row">
        <div class="col-3" id="explorer">
            <div class="card border h-100">
                <div class="card-body">
                    <ul class="tree-view"></ul>
                    <ul class="btn-bar">
                        <li><button id="createGroup" type="button">Create Group</button></li>
                        <li><button id="createUser" type="button">Add User</button></li>
                    </ul>
                </div> 
            </div>
        </div>
            
        <div class="col-sm-9" id="detail-view">
            <div class="card border h-100">
                <div class="card-body">
                    <table class="display table" id="assign-detail"> 
                        <thead>
                            <tr>
                                <td>Name</td>
                                <td>Editor</td>
                                <td>Actors</td>
                            </tr>
                        </thead>
                        <tbody>

                        </tbody>
                    </table>
                </div> 
            </div>
            
        </div>  
            
    
        
    </div>

</div>



{% endblock %}

bbwdesk/templates/bbwdesk/index_content.html
{% extends 'bbwdesk/base.html' %}
{% load bbwdesk_extras %}


{% block content_block %}
{% load static %}
<script type="text/javascript" src="{% static "bbwdesk/js/taskIndex.js" %}"></script>
<!-- DataTables JS -->
<script src="{% static "base/js/addons/datatables2.min.js" %}" type="text/javascript"></script>
<!-- DataTables Select JS -->
<script src="{% static "base/js/addons/datatables-select2.min.js" %}" type="text/javascript"></script>

<div class="jumbotro text-center" id="dashboard-head">
    <h2> User-Dashboard </h2>
</div>

<div class="container-fluid" >
    <div class="row">
        <div class="col-sm-3 " id="assignments">
            <table id="assignment_table" class="table  table-bordered table-sm" cellspacing="0"
            width="100%">
                <thead>
                    <tr>
                        <th class="th-sm">My Assigments
                        </th>
                    </tr>
                </thead>
                <tbody>
                    
                    {% for assign in assignments %}
                    <tr>
                        <td assign_id="{{ assign.id }}">{{ assign.name }}</td>
                    </tr>
                    {% endfor %}
                    
                </tbody>
            </table>
        </div>
        
        
        <div class="col-sm-9 " id="tasks">
            <h3>My Tasks</h3>
                <table id="obj-table" 
                class="table table-hover table-bordered " 
                cellspacing="0"
                width="100%" >
                    <thead>
                    <tr>
                        <th class="th">Task</th> 
                        <th class="th">Actors</th>
                        <th class="th">Priority</th>
                        <th class="th">Status</th>
                        <th class="th">Deadline</th>
                    </tr>
                    </thead>
                    
                    <tbody>
               
                    </tbody>
                </table>
        </div>
    </div>
</div>


{% endblock %}

bbwdesk/templates/bbwdesk/submission_page_content.html
{% extends 'bbwdesk/base.html' %}
{% load bbwdesk_extras %}

{% block css-block %}

{% endblock%}

{% block content_block %}



{% endblock %}

bbwdesk/templates/bbwdesk/task_create_content.html
{% extends 'bbwdesk/base.html' %}
{% load bbwdesk_extras %}


{% block content_block %}

<form action="" method="POST"> 
    {% csrf_token %}
    <table>
        {{ form }}
    </table>

    <input type="submit" value="Create Task">
</form>


{% endblock %}

bbwdesk/templates/bbwdesk/task_delete_content.html
{% extends 'bbwdesk/base.html' %}
{% load bbwdesk_extras %}


{% block content_block %}

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ task }}"?</p>
    <input type="submit" value="Confirm">
</form>   

{% endblock %}

bbwdesk/templates/bbwdesk/task_detail.html
{% extends 'bbwdesk/base.html' %}
{% load bbwdesk_extras %}

{% block content_block %}
<ul class="list-group list-group-flush">
    
    <li class="list-group-item">
        <div class="container">
            <p><strong>Title: </strong> {{task.title}} </p>
            <p><strong>Description: </strong> {{ task.description }}</p>
            <p><strong>Users: </strong> 
            {% for user in users %} 
               {{ user.initals }}
            {% endfor %}</p>
            <p><strong>Deadline: </strong> {{ task.deadline }}</p>
        </div>
    </li>
    <li class="list-group-item">
        <div class="container">
            <p><strong>Priority: </strong> {{ task.priority }} </p>
            <p><strong>Status: </strong> {{ task.status }}</p>
            <p><strong>Progress: </strong> {{ task.progress }}</p>
        </div>
    </li>
    <li class="list-group-item">
        <div class="container">
            <button type="button" class="btn btn-primary " onclick="location.href='{% url 'bbwdesk:task_edit' task.id %}';">Edit Task</button>
            <button type="button" class="btn btn-primary " onclick="location.href='{% url 'bbwdesk:task_submit' task.id %}';"> Submit Results</button>
        </div>
    </li>
</ul>


{% endblock %}

bbwdesk/templates/bbwdesk/task_edit_content.html
{% extends 'bbwdesk/base.html' %}
{% load bbwdesk_extras %}

{% block css-block %}
    
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'bbwdesk/css/taskEdit.css' %}">

{% endblock %}

{% block content_block %}

    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Save">
    </form>
    <form action="{% url 'bbwdesk:task_delete' task.id %}" method="GET"> {% csrf_token %}
        <input type="submit" value="Delete">
    </form>


{% endblock %}

bbwdesk/templates/bbwdesk/users_account_create.html
{% extends 'bbwdesk/base.html' %}
{% load bbwdesk_extras %}

{% block css-block %}

{% endblock%}

{% block content_block %}
<ul class="list-group list-group-flush">
    
    <li class="list-group-item">
        <div class="container"> 
            {% csrf_token %}
            <form action="" method="POST">
                {% csrf_token %}
               
                <input type="submit" value="Create User">
            </form>
       
        </div>
    </li>
    <li class="list-group-item">
        <div class="container">
  
        </div>
    </li>
    <li class="list-group-item">
        <div class="container">
            <button type="button" class="btn btn-primary " onclick="location.href='#';">Delete User</button>
        </div>
    </li>

</ul>

{% endblock %}