aduseradmin/urls.py
from django.urls import path
from .  import  views

app_name = "aduseradmin"
urlpatterns = [
    path('login/', views.loginPage, name='login'),
    path('register/', views.registerPage, name='register'),
   
    # universal views for logged in users
    path('logout/', views.logoutPage, name='logout'),
    path('account/', views.accountPage, name='account'),

    # Administration of Accounts (Staff_only)
    # path('admin/', views.adminPage, name='admin'),
    
    # groups
    path('groups/create', views.createGroup, name='group_create'),
    path('groups/<int:pk>/delete', views.deleteGroup, name='group_delete'),
    path('groups/<int:pk>/update', views.updateGroup, name='group_upate'),

    # users
    path('user/<int:pk>/view', views.viewUser, name='user_view'),
    path('user/<int:pk>/delete', views.deleteUser, name='user_delete'),
    path('user/<int:pk>/update', views.updateUser, name='user_update'),
    path('createuser/', views.createUser, name='user_create'),
]

bbwdesk/urls.py
from django.urls import path

from . import views
from . import restViews

app_name = 'bbwdesk'
urlpatterns = [
     # index
     path('', views.index, name='index'), #user dashboard
     path('adminboard/', views.adminPage, name='admin'),
     # task 
     path('taskcreate/', views.task_create, name='task_create'),
     path('<int:pk>/edit/', views.task_edit, name='task_edit'),
     path('<int:pk>/delete/', views.task_delete, name='task_delete'),
     path('<int:pk>/view/', views.TaskDetail.as_view(), 
          {'task_list.html':'bbwdesk/task_view_content.html'}, name='task_view'),
     path('<int:pk>/submit/', views.taskSubmitPage, name='task_submit'),
     # assignment Urls
     path('assignment/<int:pk>/', views.assignmentPage, name='assginment_view'),

     # API
     path('getGroupList/', views.getGroupList, name='ajax_grouplist'),
     path('objByAssignId/', views.getObjectsbyAssignment),
     path('assign/', restViews.AssignmentSet.as_view(), name='AssignmentSet'),
     path('assign/<int:pk>', restViews.AssignmentDetail.as_view(), name='AssignmentDetail'),
     path('assignNested/', restViews.AssignmentNestedSet.as_view(), name='NestedAssignmentSet'),
     path('userSet/', restViews.ExtendedUserSet.as_view(), name='UserSet'),
     path('assignObjSet/', restViews.AssignmentObjectSet.as_view(), name='AssignObjSet'),
]

fiaehome/urls.py
from django.contrib import admin
from django.urls import path, include 

app_name='fiaehome'
urlpatterns = [
    path('', include('bbwdesk.urls')),
    path('admin/', admin.site.urls),
    path('', include('aduseradmin.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

aduseradmin/models.py
from django.db import models

# Create your models here.

aduseradmin/forms.py
from django.forms import ModelForm
from bbwdesk.models import UserDetail
from django.contrib.auth.models import User


class UserDetailForm(ModelForm):
    class Meta:
        model = UserDetail
        fields = ['initals','user']

aduseradmin/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from bbwdesk.decorators import ajax_required 

from bbwdesk.models import UserDetail
from .forms import UserDetailForm

import copy

"""
     Account Pages that dont require a login
"""

def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('bbwdesk:index')
        else:
            messages.info(request, 'Username OR password is incorrect')

    return render(request, 'aduseradmin/users_login_content.html')


def registerPage(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')

            messages.success(request, 'Account was created for ' + user)

            return redirect('aduseradmin:login')
    else:
        form = UserCreationForm()

    context = {'form': form}
    return render(request, 'aduseradmin/users_register_content.html', context)


"""
    Accout Management Pages
"""
@login_required
def accountPage(request):
    return render(request, 'aduseradmin/account_management.html')

@login_required
def logoutPage(request):
    logout(request)
    return redirect('bbwdesk:index')


"""
    Group Managment Views ( Staff Only )
"""
@login_required
@ajax_required
def createGroup(request):
    return HttpResponse("Hi")

@login_required
@ajax_required
def deleteGroup(request, pk):
    return HttpResponse("Hi")

@login_required
@ajax_required
def updateGroup(request, pk):
    return HttpResponse("Hi")


"""
    User Management Views (Staff Only)
"""
@login_required
def viewUser(request, pk):
    user = User.objects.get(pk=pk)
    detail = UserDetail.objects.get(user=user.pk)

    context = {'user': user, 'detail' : detail}

    return render(request, 'aduseradmin/users_account_view.html', context)

@login_required
def deleteUser(request, pk):
    user = get_object_or_404(User, pk=pk)
        
    if request.method == 'POST': # Confirmed Delete
        UserDetail.objects.get(user=user.pk).delete()
        user.delete()
        return redirect('bbwdesk:index')
        
    return render(request, 'aduseradmin/users_account_delete.html', {'user' : user })

@login_required
def updateUser(request, pk):
    user = User.objects.get(pk=pk)
    userDetail = UserDetail.objects.get(user=user.id)
    

    if request.method == 'POST':
        # Filter Post for the models
        user.username = request.POST.get('username')
        user.first_name =  request.POST.get('first_name')
        user.last_name =  request.POST.get('last_name')

        userDetail.intials = request.POST.get('intials')
        
        user.save()
        userDetail.save()

        messages.success(request, 'Account-Data from' + user.username +' has been updated')

        return redirect('aduseradmin:user_update', pk)
    elif request.method == 'GET':
        userDetailForm = UserDetailForm(instance=userDetail)
        userForm = UserChangeForm(instance=user)
        
        context = {'user_f': userForm , 'detail_f' : userDetailForm}
        
        return render(request, 'aduseradmin/users_account_update.html', context)
    

@login_required
def createUser(request):
    if request.method == 'POST':
        u_form = UserCreationForm(
            { 'username' : request.POST.get('username'),
             'password1' : request.POST.get('password1'),
             'password2' : request.POST.get('password2')}
        )
    
        
        if u_form.is_valid():
            user = u_form.save()
            d_form = UserDetailForm({ 'initals' : request.POST.get('initals'),
                'user' : user.pk
            })
            
            if d_form.is_valid():  
                d_form.save()

                messages.success(request, 'Account was created for ' + user.username)
                return redirect('aduseradmin:user_view', user.pk)
            else: # d_form not valid
                user.delete()
                messages.error(request, 'User not created')  
        
    
    else: # method == 'GET'
        u_form = UserCreationForm()
        d_form = UserDetailForm()


    context = { 'user_f': u_form, 'detail_f': d_form }
    return render(request, 'aduseradmin/users_account_create.html', context)

aduseradmin/templates/aduseradmin/users_account_create.html
{% extends 'bbwdesk/base.html' %}
{% load bbwdesk_extras %}

{% block css-block %}

{% endblock%}

{% block content_block %}

<form action="" method="POST"> 
    {% csrf_token %}
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <div class="container">
                    {{ user_f.username.label }} {{ user_f.username }}
                    Passwort {{ user_f.password1 }} 
                    Passwort bestätigen {{ user_f.password2 }} 
                    {{ detail_f.initals.label }} {{ detail_f.initals }}
                    <input type="submit" value="Create">
            </div>
        </li>
        {% for msg in messages%}
        <li><p id="messages">{{msg}}</p></li>
    {% endfor %}
    </ul>
</form>

{% endblock %}

aduseradmin/templates/aduseradmin/users_account_delete.html
{% extends 'bbwdesk/base.html' %}
{% load bbwdesk_extras %}

{% block css-block %}

{% endblock%}

{% block content_block %}
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ user }}"?</p>
    <input type="submit" value="Confirm">
</form>   
{% endblock %}

aduseradmin/templates/aduseradmin/users_account_update.html
{% extends 'bbwdesk/base.html' %}
{% load bbwdesk_extras %}

{% block css-block %}

{% endblock%}

{% block content_block %}
<ul class="list-group list-group-flush">
    
    <li class="list-group-item">
        <div class="container"> 
            {% csrf_token %}
            <form action="" method="POST">
                {% csrf_token %}
                {{ user_f.username.label }} {{ user_f.username }}
                {{ user_f.first_name.label}} {{ user_f.first_name }} 
                {{ user_f.last_name.label}} {{ user_f.last_name }} 
                {{ detail_f.initals.label }} {{ detail_f.initals }}
                <input type="submit" value="Save">
            </form>
       
        </div>
    </li>
    <li class="list-group-item">
        <div class="container">
  
        </div>
    </li>
    <li class="list-group-item">
        <div class="container">
            <button type="button" class="btn btn-primary " onclick="location.href='#';">Delete User</button>
        </div>
    </li>

</ul>

{% endblock %}

aduseradmin/templates/aduseradmin/users_account_view.html
{% extends 'bbwdesk/base.html' %}
{% load bbwdesk_extras %}

{% block css-block %}

{% endblock%}

{% block content_block %}
<ul class="list-group list-group-flush">
    
    <li class="list-group-item">
        <div class="container">
            <p>{{user.username}}</p>
            <p>{{user.first_name}}</p>
            <p>{{user.last_name}}</p>
            <p>{{detail.initals}}</p>
        </div>
    </li>
    <li class="list-group-item">
        <div class="container">
  
        </div>
    </li>


</ul>

{% endblock %}

aduseradmin/templates/aduseradmin/users_login_content.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #ffffff !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #317f43;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #ffa500 !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>
        
                {% for msg in messages%}
					<p id="messages">{{msg}}</p>
				{% endfor %}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'aduseradmin:register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

aduseradmin/templates/aduseradmin/users_register_content.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
						{% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{ form.username }}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{ form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>
		
				{% for msg in messages%}
					<p id="messages">{{msg}}</p>
				{% endfor %}


				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'aduseradmin:login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Enter password...';
		form_fields[3].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>